name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Congratulations on publishing your first issue! ✅"
        pr-message: "Thank you very much for creating a PR in our community. Your PR will now be reviewed by any of our maintainers soon! 🚩"
